//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::sys_rel_role_resource::Entity as SysRelRoleResource;
pub use super::sys_rel_user_role::Entity as SysRelUserRole;
pub use super::sys_resource::Entity as SysResource;
pub use super::sys_role::Entity as SysRole;
pub use super::sys_user::Entity as SysUser;
