//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uname: String,
    pub psw: String,
    pub nickname: Option<String>,
    pub sex: Option<String>,
    pub mobile: Option<String>,
    pub email: Option<String>,
    pub create_at: Option<DateTimeUtc>,
    pub create_by: Option<i32>,
    pub update_at: Option<DateTimeUtc>,
    pub update_by: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
